// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpWC7dIaXpp8ImqPHqXSQ4vYTOSFEmqw',
    appId: '1:178361432512:android:974725d1638fdd51a57025',
    messagingSenderId: '178361432512',
    projectId: 'fooddelivery-f3e81',
    storageBucket: 'fooddelivery-f3e81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgJScdvIPGaGg1XSG6sTTIVvt8aoV6Bk',
    appId: '1:178361432512:ios:dfa7282f6042c524a57025',
    messagingSenderId: '178361432512',
    projectId: 'fooddelivery-f3e81',
    storageBucket: 'fooddelivery-f3e81.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAppEmilioPuigcerver',
  );
}

